language: ruby
sudo: false
cache: bundler
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
rvm:
  - 2.6.3
  - ruby-head
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_6_1.gemfile
  - gemfiles/rails_master.gemfile
  - Gemfile
matrix:
  fast_finish: true